### ISSUE TITLE
Ombi error after requesting TV/movie - "There was an error in your request."

### ISSUE THREAD

**Issue by trillex** [v0idp/Mellow#20]
Hi,

Hopefully I have gathered all the information I can.

I'm using Mellow on a standalone docker, separate from Ombi (Running on Windows). The connectivity seems fine and information is pulled from Ombi without issue, but as soon as I request the movie, the following error is shown in the log for Mellow:

`2019-04-23T14:10:43.787137224Z null`

The bot gives the standard error message to the requester: 

`@trillex, There was an error in your request.`

Ombi gives the following log output when this happens: 

```
fail: Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
System.InvalidOperationException: StatusCode cannot be set because the response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAlwaysRunResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.ValidateApiKey(HttpContext context, RequestDelegate next, String key) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 115
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ApiKeyMiddlewear.cs:line 34
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\ErrorHandlingMiddlewear.cs:line 24
```

The request is added to Ombi, however, and goes through the normal Ombi motions. 

The issue might not be Mellow at all, but Ombi, but I believe I might need your help to pull out some additional information to present to the Ombi fellows.

**Comment by Alpha5k** [comment]
Known issue. Switch to develop branch or add a username to the Ombi settings in Mellow.

**Comment by trillex** [comment]
Holy heck, that was a fast response. 

Adding my Ombi username solved the issue. 

Closing this issue, fastest ever. Thank you very much.
