### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by jfairham1** [v0idp/Mellow#25]
Hi
I'm getting the following in mellow docker logs when issuing an command.

!MOVIE <NAME>

BotClient ready and logged in as *****#*** (****************************). Prefix set to !. Use !help to view the commands list!

SyntaxError: Unexpected token < in JSON at position 1 at JSON.parse (<anonymous>)
at get.then (/usr/src/app/src/commands/ombi/movie.js:98:21)
at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:694:18)
at _drainQueueStep (/usr/src/app/node_modules/bluebird/js/release/async.js:138:12)
at _drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:131:9)
at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:147:5)
at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/app/node_modules/bluebird/js/release/async.js:17:14)
at processImmediate (internal/timers.js:443:21)

I have double checked token at seems ok.

**Comment by jfairham1** [comment]
Hi, ive sorted this hadnt put docker container IP in the host field
