### ISSUE TITLE
PM2 error: app=index id=0 does not have a pid

### ISSUE THREAD

**Issue by SerinitySW** [v0idp/Mellow#49]
I've been running Mellow in a docker container on my unraid server, with terrific results! However I believe a few nights ago it auto-updated, now giving me these errors in the logs:

Nothing has changed configuration wise, although apart of my troubleshooting was deleting the image / reinstalling, .bak'ing the settings files, etc.

```2020-01-15T17:46:09: PM2 log: App [index:0] starting in -fork mode-
2020-01-15T17:46:09: PM2 log: App [index:0] online
Error: Cannot find module '/usr/src/app/data/settings.json'

Require stack:
- /usr/src/app/src/Database.js
- /usr/src/app/src/index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:51:29)
at require (internal/modules/cjs/helpers.js:74:18)
at new Database (/usr/src/app/src/Database.js:14:26)
at start (/usr/src/app/src/index.js:7:25)
at Object.<anonymous> (/usr/src/app/src/index.js:16:1)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/usr/src/app/src/Database.js', '/usr/src/app/src/index.js' ]
}
2020-01-15T17:46:09: PM2 log: App [index:0] exited with code [1] via signal [SIGINT]
2020-01-15T17:46:09: PM2 log: Script /usr/src/app/src/index.js had too many unstable restarts (16). Stopped. "errored"
2020-01-15T17:46:10: PM2 log: 0 application online, retry = 3
2020-01-15T17:46:12: PM2 log: 0 application online, retry = 2
2020-01-15T17:46:14: PM2 log: 0 application online, retry = 1
2020-01-15T17:46:16: PM2 log: 0 application online, retry = 0
2020-01-15T17:46:16: PM2 log: Stopping app:index id:0
2020-01-15T17:46:16: PM2 error: app=index id=0 does not have a pid

2020-01-15T17:46:16: PM2 log: PM2 successfully stopped```

**Comment by v0idp** [comment]
please switch to the develop tag and see if that fixes your issue.

EDIT: merged all the changes to master. If you pull the latest image it should work just fine.
