### ISSUE TITLE
Error with Ombi response when accepted item to download

### ISSUE THREAD

**Issue by ch1nch4ch4** [v0idp/Mellow#67]
Describe the bug
Ombi version: 3.0.3421
Mellow - https://github.com/Cloudbox/Community/wiki/Mellow-Discord-Bot

The bot connects to Ombi and everything works apart from the confirmation response from Ombi to Mellow. The Mellow DEVs have advised that this issue seems to be Ombi related hence me logging it.

The Ombi logs details the following

2020-01-17 14:58:26.622 +01:00 [Debug] Searching : "loser"
2020-01-17 14:58:28.028 +01:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.Mo$
2020-01-17 14:58:57.670 +01:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.Mo$
2020-01-17 14:59:23.272 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/321457
2020-01-17 14:59:23.272 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/145181
2020-01-17 14:59:23.272 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/79629
2020-01-17 14:59:23.451 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/273826
2020-01-17 14:59:23.451 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/279269
2020-01-17 14:59:23.767 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/256880
2020-01-17 14:59:24.054 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/360779
2020-01-17 14:59:24.779 +01:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://webservice.fanart.tv/v3/tv/265359

To Reproduce

Go to discord request tv/movie and accept version
Expected behavior
Confirmation message stating X Move/TV Show accepted by user "X"

Screenshots
N/A

Logs (Logs directory where Ombi is located)
Log extract above

Desktop (please complete the following information):

OS: Linux
Ombi Version (please complete the following information):

Version as above

**Comment by v0idp** [comment]
Hey I just checked the issue you made ok ombi and it appears we had a misunderstanding. Der original error message you posted here is related to ombi actually. But it seems you posted another error message on the original issue which was actually related to mellow and had nothing to do with the original post you made. The error message I'm talking about is only related to mellow and has nothing to do with the first message you posted. Sorry for not telling you ! 

```DiscordAPIError: Invalid Form Body embed.fields[0].value: Must be 1024 or fewer in length. at RequestHandler.execute (/home/mellow/node_modules/discord.js/src/rest/RequestHandler.js:170:25) at processTicksAndRejections (internal/process/task_queues.js:93:5) { name: 'DiscordAPIError', message: 'Invalid Form Body\nembed.fields[0].value: Must be 1024 or fewer in length.', method: 'post', path: '/channels/XXXXXXXXXXXX/messages', code: 50035, httpStatus: 400 } { error: null, body: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n' + '<html><head>\n' + '<title>502 Proxy Error</title>\n' + '</head><body>\n' + '<h1>Proxy Error</h1>\n' + '<p>The proxy server received an invalid\r\n' + 'response from an upstream server.<br />\r\n' + 'The proxy server could not handle the request<p>Reason: <strong>Error reading from remote server</stro$ '</body></html>\n' }```

**Comment by ch1nch4ch4** [comment]
Hi, I have just copied across the issue logged against Ombi so not sure what error message you are referring to. 

https://github.com/tidusjar/Ombi/issues/3351

The issue remains that when Ombi sends the response back to Mellow, mellow doesn't get the correct reply or doesn't get/see the reply at all.

**Comment by v0idp** [comment]
Can you tell me how to reproduce this issue ?

**Comment by ch1nch4ch4** [comment]
Yeah sure, cloned the mellow repo, ran npm run restart followed by npm run start. Let it start and connect to Discord.

From Discord, search for any TV-Show / Movie, select the appropriate number and then hit the down arrow to confirm selection. It's the confirmation response that is detailing the error in Discord. 

If I look in Sonarr/Radarr the show/movie is there so it has sent the request OK

Thanks

**Comment by v0idp** [comment]
Does this apply for every show and movie and can you post the error message from mellow after that happens ?

**Comment by ch1nch4ch4** [comment]
yes that's correct

Discord error 'There was an error in your request.'

How would I check the logs if the Tautulli is running as a service?

**Comment by v0idp** [comment]
Please check the logs in the mellow container.

**Comment by ch1nch4ch4** [comment]
Hi its not a container.. I am using NPM

**Comment by v0idp** [comment]
Then check the logs in your console where it's running please. I need to see what's happening upon failure on your end.

**Comment by zenjabba** [comment]
I was able to reproduce this, but updating to the latest version of Ombi on the develop branch (3.0.4958) fixed it.

**Comment by ch1nch4ch4** [comment]
So I updated the bot to version 2.0 and the issues is now resolved.
