### ISSUE TITLE
Adding TV show does not work

### ISSUE THREAD

**Issue by moutonnoireu** [v0idp/Mellow#95]
Here are the logs when trying to add a serie (pm2 logs) :

```/root/.pm2/logs/index-error.log last 15 lines:
0|index    | TypeError: series.genres.contains is not a function
0|index    |     at buildSonarrSeries (/home/mellow/Mellow/src/api/helpers/sonarr.js:26:23)
0|index    |     at addSeries (/home/mellow/Mellow/src/bots/services/sonarr.js:75:23)
0|index    |     at /home/mellow/Mellow/src/bots/services/sonarr.js:101:20
0|index    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|index  | TypeError: series.genres.contains is not a function
0|index  |     at buildSonarrSeries (/home/mellow/Mellow/src/api/helpers/sonarr.js:26:23)
0|index  |     at addSeries (/home/mellow/Mellow/src/bots/services/sonarr.js:75:23)
0|index  |     at /home/mellow/Mellow/src/bots/services/sonarr.js:101:20
0|index  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|index  | TypeError: series.genres.contains is not a function
0|index  |     at buildSonarrSeries (/home/mellow/Mellow/src/api/helpers/sonarr.js:26:23)
0|index  |     at addSeries (/home/mellow/Mellow/src/bots/services/sonarr.js:75:23)
0|index  |     at /home/mellow/Mellow/src/bots/services/sonarr.js:101:20
0|index  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I tried to add 3 differents series, same bug occured.

Any idea what is causing this ?

**Comment by v0idp** [comment]
update to latest develop, this was fixed. a7c174e
